name: carcure
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.6 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_riverpod: ^2.4.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  google_sign_in: ^5.0.7
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  country_pickers: ^2.0.0
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  carousel_slider: ^4.2.1
  calendar_date_picker2: ^0.5.3
  grouped_list: ^5.1.2
  google_maps_flutter: ^2.5.0
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Preahvihear
      fonts: 
        - asset: assets/fonts/PreahvihearRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
